### ISSUE TITLE
The workflow failed because of the failure to build CKB

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb-docker-builder#22]
https://github.com/nervosnetwork/ckb-docker-builder/actions/runs/7176444514/job/19542669772

Since the two projects have reciprocal dependency on each other, I'll publish the docker image manually first.

**Comment by doitian** [comment]
aarch64 still fails https://github.com/nervosnetwork/ckb-docker-builder/actions/runs/7193933806/job/19596081552

**Comment by eval-exec** [comment]
> aarch64 still fails https://github.com/nervosnetwork/ckb-docker-builder/actions/runs/7193933806/job/19596081552

This PR https://github.com/nervosnetwork/ckb-docker-builder/pull/26 want to fix this.
